#!/bin/sh
cd "${0%/*}" || exit    # Run from this directory

#Delete files in 0/ directory
find 0/ -maxdepth 1 -type f -delete

#Copy the .orig
cp -a 0/orig/. 0/

#delete .orig name
for filename in 0/*; do mv "./$filename" "./$(echo "$filename" | sed -e 's/.orig//g')";  done

#Clean log files
find -type f -name '*log*' -delete

rm -rf processor*

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

#Clean case
cleanCase()
#------------------------------------------------------------------------------
